name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - gh-pages
  schedule:
    - cron: '0 1 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1.1.0
      with:
        submodules: recursive
    - name: Build and Deploy
      uses: renzhaosy/hexo-deploy-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN}}
        PUBLISH_REPOSITORY: qinglong-kooboo/qinglong-kooboo.github.io # The repository the action should deploy to.
        BRANCH: master # The branch the action should deploy to.
        PUBLISH_DIR: ./public # The folder the action should deploy.
